// memoire_react/src/components/Type/Create.js
﻿import {useState} from "react";


function Create() {
    const [inputs, setInputs] = useState({});

    const handleChange = (event) => {
        const name = event.target.name;
        const value = event.target.value;
        setInputs(values => ({...values, [name]: value}))
    }

    const submitData = async (event) => {
        event.preventDefault();
        const response = await fetch('https://localhost:7009/api/type', {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                Label: inputs.label
            })
        });
        if (response.status === 200) {
            alert("Create with sucess")
        }
        else{
            alert("An error occured");
        }
    }
    return (
        <form onSubmit={submitData}>
            <div>
                <label>Label:
                    <input
                        type="text"
                        name="label"
                        value={inputs.label || ""}
                        onChange={handleChange}
                    />
                </label>
            </div>

            <div>
                <input type="submit" value="Create"/>
            </div>
        </form>
    )
}

export default Create;

// memoire_vue/src/components/Type/Create.vue
<template>
    <div>
        <form @submit.prevent="submitForm">
            <div>
                <label for="Label">label:</label>
                <input type="text" id="Label" v-model="form.Label" required />
            </div>
            <button type="submit">Create</button>
        </form>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                form: {
                    Label: ''
                }
            };
        },
        methods: {
            async submitForm() {
                try {
                    const response = await fetch('https://localhost:7009/api/type', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            Label: this.form.Label
                        })
                    });
                    
                    console.log(response);
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    alert("Create with sucess");
                } catch (error) {
                    console.error('Erreur lors de la soumission du formulaire:', error);
                }
            }
        }
    };
</script>
