// memoire_vue/src/components/PublishingHouse/Create.vue
<template>
    <div>
        <form @submit.prevent="submitForm">
            <div>
                <label for="name">name:</label>
                <input type="text" id="name" v-model="form.name" required />
            </div>
            <div>
                <label for="startYear">start Year:</label>
                <input type="number" id="startYear" v-model="form.startYear" required />
            </div>
            <button type="submit">Create</button>
        </form>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                form: {
                    name: '',
                    startYear:''
                }
            };
        },
        methods: {
            async submitForm() {
                try {
                    const response = await fetch('https://localhost:7009/api/PublishingHouse', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            Name: this.form.name,
                            StartYear: this.form.startYear
                        })
                    });
                    
                    console.log(response);
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    alert("Create with sucess");
                } catch (error) {
                    console.error('Erreur lors de la soumission du formulaire:', error);
                }
            }
        }
    };
</script>

// memoire_react/src/components/PublishingHouse/Create.js
﻿import {useState} from "react";


function Create() {
    const [inputs, setInputs] = useState({});

    const handleChange = (event) => {
        const name = event.target.name;
        const value = event.target.value;
        setInputs(values => ({...values, [name]: value}))
    }

    const submitData = async (event) => {
        event.preventDefault();
        const response = await fetch('https://localhost:7009/api/publishingHouse', {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                name: inputs.name,
                startYear: inputs.startYear
            })
        });
        if (response.status === 200) {
            alert("Create with sucess")
        }
        else{
            alert("An error occured");
        }
    }
    return (
        <form onSubmit={submitData}>
            <div>
                <label>Name:
                    <input
                        type="text"
                        name="name"
                        value={inputs.name || ""}
                        onChange={handleChange}
                    />
                </label>
                
            </div>
            <div>
                <label>Start year:
                    <input
                        type="number"
                        name="startYear"
                        value={inputs.startYear || ""}
                        onChange={handleChange}
                    />
                </label>
            </div>
            <div>
                <input type="submit" value="Create"/>
            </div>
        </form>
    )
}

export default Create;
