// memoire_vue/src/components/PublishingHouse/Update.vue
<template>
    <div>
        <form @submit.prevent="submitForm">
            <div>
                <label for="name">name:</label>
                <input type="text" id="name" v-model="publishingHouse.name" required />
            </div>

            <div>
                <label for="startYear">startYear:</label>
                <input type="number" id="startYear" v-model="publishingHouse.startYear" required />
            </div>
            <button type="submit">Update</button>
        </form>
    </div>
</template>
<script>
    export default {
        name: 'Update',
        data() {
            return {
                id: null,
                publishingHouse: null
            };
        },
        methods: {
            async fetchData() {
                const response = await fetch('https://localhost:7009/api/publishingHouse/'+this.id, {
                    headers: {
                        'Content-Type': 'application/json'
                    }
                });
                this.publishingHouse = await response.json();
            },
            async submitForm() {
                try {
                    const response = await fetch('https://localhost:7009/api/publishingHouse', {
                        method: 'PUT',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            Id: this.publishingHouse.id,
                            Name: this.publishingHouse.name,
                            StartYear: this.publishingHouse.startYear
                        })
                    });
                    if (response.status === 200) {
                        alert("Updated with sucess")
                    }
                    else {
                        alert("An error occured");
                    }
                } catch (error) {
                    console.error('Erreur lors de la soumission du formulaire:', error);
                }
            }
        },
        created() {
            this.id = this.$route.params.id;
            this.fetchData();
        }
    }
</script>

// memoire_react/src/components/PublishingHouse/Update.js
﻿import {useEffect, useState} from "react";
import {
    BrowserRouter as Router,
    Link,
    Route,
    Routes,
    useParams,
} from "react-router-dom";


function Update() {
    const [inputs, setInputs] = useState({});

    const { id } = useParams();
    const handleChange = (event) => {
        const name = event.target.name;
        const value = event.target.value;
        setInputs(values => ({...values, [name]: value}))
    }
    useEffect(() => {
        populatePublishingHouse();
    }, []);

    const updateData = async (event) => {
        event.preventDefault();
        const response = await fetch('https://localhost:7009/api/PublishingHouse', {
            method: 'PUT',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                Id : inputs.id,
                Name: inputs.name,
                StartYear: inputs.startYear
            })
        });
        if (response.status === 200) {
            alert("Updated with sucess")
        }
        else{
            alert("An error occured");
        }
    }
    async function populatePublishingHouse() {
        const response = await fetch('https://localhost:7009/api/PublishingHouse/'+id);
        const data = await response.json();
        setInputs(data);
    }

    return (
        <form onSubmit={updateData}>
            <div>
                <label>Name:
                    <input
                        type="text"
                        name="name"
                        value={inputs.name || ""}
                        onChange={handleChange}
                    />
                </label>
            </div>

            <div>
                <label>Start year:
                    <input
                        type="number"
                        name="startYear"
                        value={inputs.startYear || ""}
                        onChange={handleChange}
                    />
                </label>
            </div>
            <div>
                <input type="submit" value="Update"/>
            </div>
        </form>
    )
}

export default Update;
