// memoire_vue/src/components/Type/Update.vue
<template>
    <div>
        <form @submit.prevent="submitForm">
            <div>
                <label for="label">label:</label>
                <input type="text" id="label" v-model="type.label" required />
            </div>
            <button type="submit">Update</button>
        </form>
    </div>
</template>
<script>
    export default {
        name: 'Update',
        data() {
            return {
                id: null,
                type: null
            };
        },
        methods: {
            async fetchData() {
                const response = await fetch('https://localhost:7009/api/type/'+this.id, {
                    headers: {
                        'Content-Type': 'application/json'
                    }
                });
                this.type = await response.json();
            },
            async submitForm() {
                try {
                    const response = await fetch('https://localhost:7009/api/type', {
                        method: 'PUT',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            Id: this.type.id,
                            Label: this.type.label
                        })
                    });
                    if (response.status === 200) {
                        alert("Updated with sucess")
                    }
                    else {
                        alert("An error occured");
                    }
                } catch (error) {
                    console.error('Erreur lors de la soumission du formulaire:', error);
                }
            }
        },
        created() {
            this.id = this.$route.params.id;
            this.fetchData();
        }
    }
</script>

// memoire_react/src/components/Type/Update.js
﻿import {useEffect, useState} from "react";
import {
    BrowserRouter as Router,
    Link,
    Route,
    Routes,
    useParams,
} from "react-router-dom";


function Update() {
    const [inputs, setInputs] = useState({});

    const { id } = useParams();
    const handleChange = (event) => {
        const name = event.target.name;
        const value = event.target.value;
        setInputs(values => ({...values, [name]: value}))
    }
    useEffect(() => {
        populateType();
    }, []);

    const updateData = async (event) => {
        event.preventDefault();
        const response = await fetch('https://localhost:7009/api/Type', {
            method: 'PUT',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                Id : inputs.id,
                Label: inputs.label
            })
        });
        if (response.status === 200) {
            alert("Updated with sucess")
        }
        else{
            alert("An error occured");
        }
    }
    async function populateType() {
        const response = await fetch('https://localhost:7009/api/Type/'+id);
        const data = await response.json();
        setInputs(data);
    }

    return (
        <form onSubmit={updateData}>
            <div>
                <label>Label:
                    <input
                        type="text"
                        name="label"
                        value={inputs.label || ""}
                        onChange={handleChange}
                    />
                </label>
            </div>

            <div>
                <input type="submit" value="Update"/>
            </div>
        </form>
    )
}

export default Update;
