// memoire_vue/src/components/Person/Update.vue
<template>
    <div>
        <form @submit.prevent="submitForm">
            <div>
                <label for="Lastname">Lastname:</label>
                <input type="text" id="Lastname" v-model="person.lastname" required />
            </div>
            <div>
                <label for="Firstname">firstname:</label>
                <input type="text" id="Firstname" v-model="person.firstname" required />
            </div>
            <div>
                <label for="DateOfBirth">Date of birth:</label>
                <input type="date" id="DateOfBirth" v-model="formattedDateOfBirth" required />
            </div>
            <div>
                <label>
                    Gender:
                    <label>
                        <input type="radio" id="male" value="true" v-model="person.isMan">
                        <label for="male">Male</label>
                    </label>
                    <label>
                        <input type="radio" id="female" value="false" v-model="person.isMan">
                        <label for="female">Female</label>
                    </label>
                </label>
            </div>
            <button type="submit">Create</button>
        </form>
    </div>
</template>
<script>
    export default {
        name: 'Update',
        data() {
            return {
                id: null,
                person: null
            };
        },
        computed: {
            formattedDateOfBirth: {
                get() {
                    return this.person.dateOfBirth.split('T')[0];
                },
                set(value) {
                    this.person.dateOfBirth = value;
                }
            }
        },
        methods: {
            async fetchData() {
                const response = await fetch('https://localhost:7009/api/person/'+this.id, {
                    headers: {
                        'Content-Type': 'application/json'
                    }
                });
                this.person = await response.json();
            },
            async submitForm() {
                try {
                    const response = await fetch('https://localhost:7009/api/person', {
                        method: 'PUT',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            Id: this.person.id,
                            Lastname: this.person.lastname,
                            Firstname: this.person.firstname,
                            DateOfBirth: this.person.dateOfBirth,
                            IsMan: this.person.isMan ? true : false
                        })
                    });
                    if (response.status === 200) {
                        alert("Updated with sucess")
                    }
                    else {
                        alert("An error occured");
                    }
                } catch (error) {
                    console.error('Erreur lors de la soumission du formulaire:', error);
                }
            }
        },
        created() {
            this.id = this.$route.params.id;
            this.fetchData();
        }
    }
</script>

// memoire_react/src/components/Update.js
﻿import {useEffect, useState} from "react";
import {
    BrowserRouter as Router,
    Link,
    Route,
    Routes,
    useParams,
} from "react-router-dom";
import {format} from 'date-fns';


function Update() {
    const [inputs, setInputs] = useState({});

    const { id } = useParams();
    const handleChange = (event) => {
        const name = event.target.name;
        const value = event.target.value;
        setInputs(values => ({...values, [name]: value}))
    }
    useEffect(() => {
        populatePerson();
    }, []);

    const updateData = async (event) => {
        event.preventDefault();
        const response = await fetch('https://localhost:7009/api/Person', {
            method: 'PUT',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                Id : inputs.id,
                Lastname: inputs.lastname,
                Firstname: inputs.firstname,
                DateOfBirth: inputs.dateOfBirth,
                IsMan: inputs.isMale ? true : false
            })
        });
        if (response.status === 200) {
            alert("Updated with sucess")
        }
        else{
            alert("An error occured");
        }
    }
    async function populatePerson() {
        const response = await fetch('https://localhost:7009/api/Person/'+id);
        const data = await response.json();
        data.dateOfBirth = format(data.dateOfBirth, 'yyyy-MM-dd');
        setInputs(data);
    }

    return (
        <form onSubmit={updateData}>
            <div>
                <label>Lastname:
                    <input
                        type="text"
                        name="lastname"
                        value={inputs.lastname || ""}
                        onChange={handleChange}
                    />
                </label>
            </div>

            <div>
                <label>Firstname:
                    <input
                        type="text"
                        name="firstname"
                        value={inputs.firstname || ""}
                        onChange={handleChange}
                    />
                </label>
            </div>

            <div>
                <label>Date of birth:
                    <input
                        type="date"
                        name="dateOfBirth"
                        value={inputs.dateOfBirth || ""}
                        onChange={handleChange}
                    />
                </label>
            </div>

            <div>
                <label>Gender:
                    <label>
                        <input
                            type="radio"
                            name="isMale"
                            value="true"
                            defaultChecked={true}
                            onChange={handleChange}
                        />
                        Male
                    </label>

                    <label>
                        <input
                            type="radio"
                            name="isMale"
                            value="false"
                            onChange={handleChange}
                        />
                        Female
                    </label>
                </label>
            </div>
            <div>
                <input type="submit" value="Update"/>
            </div>
        </form>
    )
}

export default Update;
